<?php
// Notes App - One-Time Setup Script
// Run this once to configure database, admin user, and generate config files.

declare(strict_types=1);

// Check PHP version
if (version_compare(PHP_VERSION, '8.4.0', '<')) {
    die("PHP 8.4 or higher is required. Current version: " . PHP_VERSION);
}

// Check required extensions
$requiredExtensions = ['pdo', 'pdo_mysql', 'mbstring'];
foreach ($requiredExtensions as $ext) {
    if (!extension_loaded($ext)) {
        die("Required PHP extension missing: $ext");
    }
}

// Check if already installed
if (file_exists(__DIR__ . '/../config/db.php') || file_exists(__DIR__ . '/../config/auth.php')) {
    die("Setup already completed. Remove config/ files to re-run setup.");
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $errors = [];
    
    // Validate inputs
    $dbHost = trim($_POST['db_host'] ?? '');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';
    $adminUser = trim($_POST['admin_user'] ?? '');
    $adminPass = $_POST['admin_pass'] ?? '';
    
    if (empty($dbHost)) $errors[] = 'Database host is required.';
    if (empty($dbName)) $errors[] = 'Database name is required.';
    if (empty($dbUser)) $errors[] = 'Database user is required.';
    if (empty($adminUser)) $errors[] = 'Admin username is required.';
    if (empty($adminPass) || strlen($adminPass) < 8) $errors[] = 'Admin password must be at least 8 characters.';
    
    if (!empty($errors)) {
        showForm($errors, $_POST);
        exit;
    }
    
    // Test DB connection
    try {
        $dsn = "mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4";
        $pdo = new PDO($dsn, $dbUser, $dbPass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ]);
        
        // Import schema
        $schema = file_get_contents(__DIR__ . '/schema.sql');
        $pdo->exec($schema);
        
        // Create config directory
        if (!is_dir(__DIR__ . '/../config')) {
            mkdir(__DIR__ . '/../config', 0755, true);
        }
        
        // Generate db.php
        $dbConfig = <<<PHP
<?php
// Database Configuration - Generated by setup.php
declare(strict_types=1);

return [
    'host' => '{$dbHost}',
    'dbname' => '{$dbName}',
    'user' => '{$dbUser}',
    'pass' => '{$dbPass}',
];
PHP;
        file_put_contents(__DIR__ . '/../config/db.php', $dbConfig);
        
        // Hash password
        $passwordHash = password_hash($adminPass, PASSWORD_BCRYPT);
        
        // Generate auth.php
        $authConfig = <<<PHP
<?php
// Authentication Configuration - Generated by setup.php
declare(strict_types=1);

return [
    'username' => '{$adminUser}',
    'password_hash' => '{$passwordHash}',
];
PHP;
        file_put_contents(__DIR__ . '/../config/auth.php', $authConfig);
        
        // Create initial folder structure
        $pdo->exec("INSERT INTO folders (name, parent_id) VALUES ('Inbox', NULL)");
        
        echo "<div class='success'>Setup completed successfully!<br><br>";
        echo "<strong>Important:</strong> Delete the <code>install/</code> directory for security.<br>";
        echo "Then visit <a href='../public/'>the app</a> to log in.<br>";
        echo "Username: <strong>{$adminUser}</strong><br>";
        echo "Password: <strong>********</strong></div>";
        exit;
        
    } catch (PDOException $e) {
        $errors[] = 'Database connection failed: ' . htmlspecialchars($e->getMessage());
        showForm($errors, $_POST);
        exit;
    }
}

// Show setup form
showForm([], []);

function showForm(array $errors, array $data): void {
    $dbHost = htmlspecialchars($data['db_host'] ?? 'localhost');
    $dbName = htmlspecialchars($data['db_name'] ?? 'notes_app');
    $dbUser = htmlspecialchars($data['db_user'] ?? 'root');
    $adminUser = htmlspecialchars($data['admin_user'] ?? 'admin');
    
    echo "<!DOCTYPE html>";
    echo "<html lang='en'>";
    echo "<head>";
    echo "    <meta charset='UTF-8'>";
    echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
    echo "    <title>Notes App - Setup</title>";
    echo "    <style>";
    echo "        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 500px; margin: 40px auto; padding: 20px; background: #f8f8f8; }";
    echo "        h1 { color: #333; margin-bottom: 20px; }";
    echo "        .form-group { margin-bottom: 15px; }";
    echo "        label { display: block; margin-bottom: 5px; color: #555; }";
    echo "        input[type='text'], input[type='password'] { width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; }";
    echo "        button { background: #000; color: #fff; border: none; padding: 12px 20px; border-radius: 4px; cursor: pointer; }";
    echo "        button:hover { background: #333; }";
    echo "        .error { color: #d32f2f; margin-bottom: 15px; padding: 10px; background: #ffebee; border-radius: 4px; }";
    echo "        .success { color: #388e3c; margin-bottom: 15px; padding: 10px; background: #e8f5e9; border-radius: 4px; }";
    echo "    </style>";
    echo "</head>";
    echo "<body>";
    echo "    <h1>Notes App Setup</h1>";
    
    foreach ($errors as $error) {
        echo "    <div class='error'>{$error}</div>";
    }
    
    echo "    <form method='POST'>";
    echo "        <h2>Database Configuration</h2>";
    echo "        <div class='form-group'>";
    echo "            <label for='db_host'>Host</label>";
    echo "            <input type='text' id='db_host' name='db_host' value='{$dbHost}' required>";
    echo "        </div>";
    echo "        <div class='form-group'>";
    echo "            <label for='db_name'>Database Name</label>";
    echo "            <input type='text' id='db_name' name='db_name' value='{$dbName}' required>";
    echo "        </div>";
    echo "        <div class='form-group'>";
    echo "            <label for='db_user'>Username</label>";
    echo "            <input type='text' id='db_user' name='db_user' value='{$dbUser}' required>";
    echo "        </div>";
    echo "        <div class='form-group'>";
    echo "            <label for='db_pass'>Password</label>";
    echo "            <input type='password' id='db_pass' name='db_pass'>";
    echo "        </div>";
    echo "        <h2>Admin User</h2>";
    echo "        <div class='form-group'>";
    echo "            <label for='admin_user'>Username</label>";
    echo "            <input type='text' id='admin_user' name='admin_user' value='{$adminUser}' required>";
    echo "        </div>";
    echo "        <div class='form-group'>";
    echo "            <label for='admin_pass'>Password (min 8 chars)</label>";
    echo "            <input type='password' id='admin_pass' name='admin_pass' required>";
    echo "        </div>";
    echo "        <button type='submit'>Install</button>";
    echo "    </form>";
    echo "</body>";
    echo "</html>";
}
